# Generated by Django 5.0.6 on 2025-07-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relation', '0002_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
